# Generated by Django 5.0 on 2023-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.FileField(upload_to='img')),
                ('img_on_bg', models.FileField(upload_to='img')),
                ('linkdin_link', models.URLField()),
                ('twiter_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('icon_server_fontawesome_class', models.CharField(default='class="fas fa-edit"', max_length=200)),
                ('title_service', models.CharField(max_length=100)),
                ('desc_service', models.CharField(max_length=500)),
                ('img_projects', models.FileField(upload_to='img')),
                ('title_projects', models.CharField(max_length=100)),
                ('petit_desc_projects', models.CharField(max_length=190)),
                ('link_git_project', models.URLField(max_length=300)),
                ('my_phone', models.CharField(max_length=100)),
                ('my_gmail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
    ]
