# Generated by Django 5.0 on 2023-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_projects', models.FileField(upload_to='img')),
                ('title_projects', models.CharField(max_length=100)),
                ('petit_desc_projects', models.CharField(max_length=190)),
                ('link_git_project', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_server_fontawesome_class', models.CharField(default='class="fas fa-edit"', max_length=200)),
                ('title_service', models.CharField(max_length=100)),
                ('desc_service', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RemoveField(
            model_name='base',
            name='desc_service',
        ),
        migrations.RemoveField(
            model_name='base',
            name='icon_server_fontawesome_class',
        ),
        migrations.RemoveField(
            model_name='base',
            name='img_projects',
        ),
        migrations.RemoveField(
            model_name='base',
            name='link_git_project',
        ),
        migrations.RemoveField(
            model_name='base',
            name='petit_desc_projects',
        ),
        migrations.RemoveField(
            model_name='base',
            name='title_projects',
        ),
        migrations.RemoveField(
            model_name='base',
            name='title_service',
        ),
    ]
