# Generated by Django 5.0 on 2023-12-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_services_remove_base_desc_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='img_on_bg',
        ),
    ]
